# Generated by Django 3.1.4 on 2021-01-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_auto_20210104_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cpf',
            field=models.CharField(help_text='Somente numeros', max_length=11, unique=True),
        ),
    ]
