# Generated by Django 3.1.7 on 2021-03-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_auto_20210119_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='Fone',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='end_entrega',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='idade',
            field=models.PositiveIntegerField(),
        ),
    ]
