# Generated by Django 3.1.7 on 2021-03-17 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_auto_20210317_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='Fone',
            new_name='fone',
        ),
    ]
