# Generated by Django 3.1.4 on 2021-01-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_auto_20201228_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='cut_description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='produto',
            name='long_description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_marketing',
            field=models.FloatField(verbose_name='preco'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_marketing_promo',
            field=models.FloatField(default=0, verbose_name='preco_promo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('V', 'Variavel'), ('S', 'Simples')], default='V', max_length=1),
        ),
    ]
