# Generated by Django 3.1.7 on 2021-03-17 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_auto_20210316_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='dt_entrega',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 23, 21, 3, 36, 547071)),
        ),
    ]
