# Generated by Django 3.1.7 on 2021-03-17 13:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_auto_20210316_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='dt_entrega',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 24, 13, 29, 46, 849735, tzinfo=utc)),
        ),
    ]
